# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_management_pb2 as file__management__pb2


class FileTransferServiceStub(object):
    """El servicio que define las operaciones de subida y descarga de archivos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/file_management.FileTransferService/UploadFile',
                request_serializer=file__management__pb2.FileRequest.SerializeToString,
                response_deserializer=file__management__pb2.TransferStatus.FromString,
                )
        self.DownloadFile = channel.unary_unary(
                '/file_management.FileTransferService/DownloadFile',
                request_serializer=file__management__pb2.FileRequest.SerializeToString,
                response_deserializer=file__management__pb2.FileInfo.FromString,
                )


class FileTransferServiceServicer(object):
    """El servicio que define las operaciones de subida y descarga de archivos
    """

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__management__pb2.FileRequest.FromString,
                    response_serializer=file__management__pb2.TransferStatus.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__management__pb2.FileRequest.FromString,
                    response_serializer=file__management__pb2.FileInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_management.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """El servicio que define las operaciones de subida y descarga de archivos
    """

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_management.FileTransferService/UploadFile',
            file__management__pb2.FileRequest.SerializeToString,
            file__management__pb2.TransferStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_management.FileTransferService/DownloadFile',
            file__management__pb2.FileRequest.SerializeToString,
            file__management__pb2.FileInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
