# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_management.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66ile_management.proto\x12\x0f\x66ile_management\":\n\x08\x46ileInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\x1b\n\x0b\x46ileRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"@\n\x0eTransferStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\xaf\x01\n\x13\x46ileTransferService\x12M\n\nUploadFile\x12\x1c.file_management.FileRequest\x1a\x1f.file_management.TransferStatus\"\x00\x12I\n\x0c\x44ownloadFile\x12\x1c.file_management.FileRequest\x1a\x19.file_management.FileInfo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_management_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEINFO']._serialized_start=42
  _globals['_FILEINFO']._serialized_end=100
  _globals['_FILEREQUEST']._serialized_start=102
  _globals['_FILEREQUEST']._serialized_end=129
  _globals['_TRANSFERSTATUS']._serialized_start=131
  _globals['_TRANSFERSTATUS']._serialized_end=195
  _globals['_FILETRANSFERSERVICE']._serialized_start=198
  _globals['_FILETRANSFERSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
