# PClient/Dockerfile

# Utiliza una imagen base oficial de Python
FROM python:3.8

# Instala grpcio-tools para la compilación de archivos .proto
RUN pip install grpcio-tools

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de requisitos y los instala
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia los archivos necesarios para la aplicación
COPY . .

# Copia los archivos .proto
COPY ../protobufs/*.proto ./protobufs/

# Compila los archivos .proto a Python
RUN python -m grpc_tools.protoc -I./protobufs --python_out=. \
    --grpc_python_out=. ./protobufs/file_management.proto

# Comando para ejecutar la aplicación
CMD [ "python", "./main.py" ]
