FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# API REST
EXPOSE 3000
# gRPC
EXPOSE 50051

CMD [ "node", "index.js" ]